- src/fglm/Makefile.am
- src/fglm/fglm_core.c
- src/msolve/Makefile.am
- src/msolve/libmsolve.c
- src/neogb/Makefile.am
- src/neogb/gb.c
- src/neogb/la.h
- src/usolve/Makefile.am
- src/usolve/usolve.c
I recommend to use `make distcheck` to create source tarballs on each release (and to automatically check that this source tarball contains all files).
I had to do this for Sage packaging of `msolve` in https://trac.sagemath.org/ticket/31664
> "make dist" does not work

- doc/msolve-tutorial.tex
It must be implicitly included by some other packages in newer TeX distributions, but the tutorial fails to build using the TeX packages in Ubuntu 18.04, complaining that `\mathscr` is undefined.
> Explicitly include mathrsfs package in tutorial

- src/neogb/f4sat.c
- src/neogb/modular.c
- src/neogb/update.c
1. Fixes Gebauer Moeller implementation for f4 (e.g. eco10).
2. Fixes the application of multiple consecutive saturation steps if the intermediate f4 steps did not add new information. This is necessary in some examples at the end of the computation of f4sat's application phase.
3. Fixes printing of the round numbers for f4 and saturation steps in the application phase of f4sat.
> Fixing f4 and f4sat

- .gitignore
- Makefile.am
- configure.ac
- msolve.pc.in
This allows to check library availability from a script, get its flags etc.
Very important for projects like SageMath, so that we can easily use a system-wide version, if it's installed
> adding pkg-config file

- Makefile.am
- configure.ac
- include/Makefile.am
- include/msolve/msolve-data.h
- include/msolve/msolve.h
provide autotools magic for installing headers
In the source, msolve's headers are symbolic links in include/msolve/ pointing to .h files in src/msolve/
Copies of these files are installed in $prefix/include/msolve/
It will fix #64
> make install:  headers to $prefix/include/msolve

- src/neogb/convert.c
- src/neogb/hash.c
Optimizes the parallel addition of new basis elements in f4:
1. Sequential moving sht monomials to bht.
2. Parallel adding new polynomials to basis.
This improves runtime and memory usage particularly for bigger examples and many cores (>16).
> Addition of new basis elements in f4

- src/fglm/berlekamp_massey.c
- src/fglm/data_fglm.c
...while remaining compatible with flint2.
There are still some warnings that I think should be fixed on the flint
side, see https://github.com/flintlib/flint2/issues/1390.
> Make msolve build with flint 3 alpha

- src/msolve/iofiles.c
- src/msolve/msolve.c
- src/neogb/basis.c
- src/neogb/convert.c
- src/neogb/data.c
- src/neogb/data.h
- src/neogb/f4.c
- src/neogb/f4.h
- src/neogb/io.c
- src/neogb/meta_data.c
- src/neogb/nf.c
- src/neogb/nf.h
Adds interface for normal forms in 8/16/32 bit prime fields.
**Note:** This breaks the API, thus a new release must not be minor.
> Normal form interface

- src/upolmat/nmod_mat_poly.h
- src/upolmat/nmod_poly_mat_utils.c
- src/upolmat/nmod_poly_mat_utils.h
msolve was not compiling against the recent Flint 3.0, due to basic `nmod_poly_mat`  functions that are now part of Flint itself. This PR fixes this issue.
> fixing issue "redefinition of ..." due to new functionalities in Flint 3.0

- doc/msolve-tutorial.tex
This was causing a build error in the Debian package (see https://bugs.debian.org/1058557).
Note that the `hyperref` option is now obsolete (see https://mirror.las.iastate.edu/tex-archive/macros/latex/contrib/xcolor/xcolor.pdf), but I suppose it might be good to keep around for building the docs with older versions of TeX.
> Fix spelling of "hyperref" option to xcolor package

- src/msolve/duplicate.c
- src/msolve/lifting-gb.c
- src/msolve/msolve.c
- src/neogb/basis.c
- src/neogb/basis.h
- src/neogb/data.h
- src/neogb/f4.c
- src/neogb/hash.c
- src/neogb/hash.h
This PR fixes the parallel handling of a single globel basis hash table which could have led to segmentation faults during enlargement of the table.
> Basis hash tables

- src/msolve/main.c
There is nothing wrong with calling `msolve -h`, it should not return something that indicates an error.
This will fix #131
> exit with 0 for msolve -h

- INSTALL
- doc/msolve-tutorial.tex
Thanks to Bruno Salvy for reporting on these issues and to Ludovic Perret for giving the right configure command on MAC OS.
> Fixes INSTALL description for MAC OS users and adds a link to the interfaces in msolve-tutorial

- src/msolve/main.c
With this,
```
msolve -V
```
will print msolve's version, and
```
msolve -h
```
will also print version, like
```
msolve library for polynomial system solving, version 0.6.6
```
That's to be able to tell versions using `msolve` alone (without `pkg-config`, which is sometimes just absent, or misconfigured)
> msolve -V (and -h) to (also) print version

- src/upolmat/nmod_poly_mat_utils.c
This was preventing compilation with `-all-static` due to multiple definition of `poly_mat_shift`.
> add version checking for nmod_poly_mat_shift, introduced in flint 3.0

- src/fglm/fglm_core.c
- src/msolve/hilbert.c
- src/msolve/lifting-gb.c
- src/msolve/main.c
- src/msolve/msolve-data.h
- src/msolve/msolve.c
- src/neogb/data.h
- src/neogb/meta_data.c
The goal of this PR is to homogenize how information is printed in msolve with option -v. It takes as a template the printing of F4 and reproduces it in FGLM and the lifting of Gröbner bases over rational numbers.
Below I give examples of the output in the terminal.
For the moment, I set this PR as a draft for several reasons:
1. Do we want such a homogenized printing and so should this be done to real roots isolation as well?
2. Contrary to F4, the code does not completely rely on the md_t struct of src/neogb/data.h. Should this be corrected?
3. Some printing are sent onto stdout and some to stderr. Should this be homogenized or at least clear which stream is used for what?
Comments are welcome!
Call of msolve over rational numbers with option -P 2
```
--------------- INPUT DATA …
```
> Rework printing information for FGLM and lifting of Gröbner bases

- src/msolve/lifting-gb.c
- src/msolve/msolve.c
- src/neogb/data.h
- src/neogb/meta_data.c
Learning phase speed is now printed with other computation times.
Changing the multi-modular steps printing from stderr to stdout made it not being printed live, this PR adds some `fflush(stdout)` to return to the previous behavior.
> fix bug in print of multi-modular steps not flushing the steps

- src/msolve/lifting-gb.c
- src/msolve/lifting.c
This fixes a few compiler warnings and errors when building on 32-bit systems:
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -Wdate-time -D_FORTIFY_SOURCE=2 -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4a -msha -maes -mavx -mfma -mavx2 -mrdrnd -mbmi -mbmi2 -madx -mabm -fopenmp -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/builds/math-team/msolve/debian/output/source_dir=. -fstack-protector-strong -Wformat -Werror=format-security -c libmsolve.c  -fPIC -DPIC -o .libs/libmsolve_la-libmsolve.o
In file included from msolve.c:24,
from libmsolve.c:35:
lifting.c: In function 'copy_modular_matrix':
lifting.c:207:83: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'size_t' {aka 'unsigned int'} [-Wformat=]
207 | …
```
> Fix 32-bit build

- src/msolve/msolve-data.h
In `groebner_qq`, we try to cast a pointer to this member to a pointer to an `int64_t`, which won't work on 32-bit systems where a `long` is only 32 bits.
Of course, another option would be the following:
```diff
--- a/src/msolve/lifting-gb.c
+++ b/src/msolve/lifting-gb.c
@@ -1582,7 +1582,7 @@ gb_modpoly_t *groebner_qq(
msflags_t flags)
{
int32_t *dim_ptr = &flags->dim;
-  int64_t *dquot_ptr = &flags->dquot;
+  long *dquot_ptr = &flags->dquot;
int32_t ht_size = flags->ht_size;
int32_t nr_threads = flags->nr_threads;
int32_t max_nr_pairs = flags->max_nr_pairs;
```
`dquot_ptr` doesn't appear to actually be used yet, so I'm not sure which one would be best.
> Use int64_t instead of long for dquot member of msflags_t

- interfaces/msolve-to-maple-file-interface-macos.mpl
- interfaces/msolve-to-maple-file-interface.mpl
`fc = 0` was previously not handled in `MSolveGroebner`, causing an undefined `field_char` and subsequent failures when passed to `ToMSolve`.
Tested with the following lines, saved as `test.mpl` in the project root directory, with a global installation of `msolve` on macOS.
```maple
read("interfaces/msolve-to-maple-file-interface-macos.mpl");
MSolveGroebner([x^2 + y^2 - 4, x * y - 1], 0, [x, y], ["mspath" = "msolve"]);
```
> Allow passing the field of rational numbers in maple interface

- src/msolve/msolve.c
For elimination orders we do not provide the rational parametrisation but switch to the lifting of the DRL GB. This switch falsely depended on the setting of `info_level`, which triggered issue #192 and is fixed in this PR.
> Fix for issue #192

- src/neogb/sort_r.h
Prior to FreeBSD 14, qsort_r's arguments were the original BSD style, where the thunk was the first argument to the comparison function. However, the GNU style, where the thunk was the last argument, was eventually adopted as the POSIX standard.  FreeBSD switched to this beginning with FreeBSD 14.
So when compiling on FreeBSD, we first check to see whether to use the BSD-style or GNU-style qsort_r declaration.
This patch is based on https://github.com/noporpoise/sort_r/pull/15
> Use POSIX qsort_r on FreeBSD >= 14

- src/neogb/modular.h
When the header msolve.h is included in a C++ code, C++ compilers (e.g., g++ 14.2.0) generate an error on macos about an invalid conversion from 'void*' to 'uint32_t*':
```
/msolve/msolve/../neogb/modular.h:104:24: error: invalid conversion from 'void*' to 'uint32_t*' {aka 'unsigned int*'} [-fpermissive]
104 |     lp->p   =   realloc(lp->p, (unsigned long)(lp->ld) * sizeof(uint32_t));
|                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                        |
|                        void*
```
The function realloc returns a void* pointer but lp->p  is a uint32_t*. So a cast is required.
To reproduce the problem on macos, the C++ source code (myprog.cpp) contains only:
```
#include "msolve/msolve/msolve.h"
```
and the command line is: g++ -c myprog.cpp
> add a cast on the returned value of realloc

- src/msolve/lifting.c
I got the following warning when building msolve with LLVM Clang 19 on macOS:
```
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../.. -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -maes -g -O2 -c libmsolve.c  -fno-common -DPIC -o .libs/libmsolve_la-libmsolve.o
In file included from libmsolve.c:35:
In file included from ./msolve.c:24:
./lifting.c:763:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
763 | }
| ^
1 warning generated.
```
This PR fixes the UB.
> Fix return value of check_linear_forms

- src/neogb/symbol.c
Handles an edge case (0x0 matrices) that might occur during the tracing process.
> handles 0x0 matrix edge case
