- src/msolve/Makefile.am
- test/neogb/io/validate_input_data.c
> Fix make check

- src/fglm/fglm_core.c
- src/msolve/msolve.c
Fixes a bug that occurred on 
x, y
0
x^3,
y^3
> Bugs fixes

- src/fglm/matrix-mult.c
> Fixes HAVE_AVX2 missing macro

- src/fglm/fglm_core.c
> fixes non openmp compilation

- interfaces/msolve-to-maple-file-interface.mpl
Fixed a couple of minor bugs and warnings
> Minor fixes in the Maple interface

- src/msolve/iofiles.c
- src/msolve/main.c
- src/neogb/stat.c
- src/usolve/tests.c
Identified by "spelling-error-in-binary" Lintian warning in draft of Debian package.
See https://salsa.debian.org/math-team/msolve/-/jobs/4150306.
> Fix several typos

- src/neogb/convert.c
- src/neogb/data.h
- src/neogb/f4.c
- src/neogb/hash.c
- src/neogb/stat.c
- src/neogb/symbol.c
- src/neogb/update.c
This code fixes and improves F4's elimination code, especially if the block to be eliminated consists of more than one variable.
> Fixes for elimination

- src/neogb/data.h
- src/neogb/f4.c
- src/neogb/f4sat.c
- src/neogb/io.c
- src/neogb/modular.c
- src/neogb/order.c
- src/neogb/tools.c
- src/neogb/update.c
This should fix the second phase of f4sat's learning implementation.
> Fixing phase 2 of F4SAT learning

- src/neogb/f4sat.c
- src/neogb/la_ff_32.c
- src/neogb/symbol.c
Fixes multi-threading for F4SAT
@jerebertho Please have a look and test it.
> F4sat threading fixes

- output_files/F4SAT-31.res
- output_files/F4SAT-byone-31.res
- output_files/bug-2nd-prime-bad.res
- output_files/bug-empty-tracer.res
- output_files/elim-31.e2.res
- output_files/elim-31.res
- output_files/elim-qq.e2.res
- output_files/elim-qq.res
- output_files/one-qq.g2.res
- src/msolve/iofiles.c
- src/msolve/lifting-gb.c
Reintroduces "#" as prefix for Gröbner basis meta data (fixing Maple file interface).
> Gröbner basis meta data

- src/msolve/lifting-gb.c
- src/msolve/msolve.c
* bug fix (lifting of parametrizations)
* bug fix (handling bad primes when lifting Groebner bases)
> Additional bug fixes

- configure.ac
- src/msolve/Makefile.am
- src/neogb/Makefile.am
1. `AC_CHECK_LIB` -> `AC_SEARCH_LIBS`.
2. Adds header files to build environment.
> Build system fixes

- src/neogb/la_ff_16.c
- src/neogb/la_ff_32.c
- src/neogb/la_ff_8.c
Adds support for ARM Neon intrinsics in sparse linear algebra for f4.
@williamstein Thanks for supporting msolve via giving us access to your Mac Studio, helped a lot optimizing this PR.
> ARM Neon support for f4

- Makefile.am
- configure.ac
Removes broken test, see #110 .
> Bad test removal

- Makefile.am
- configure.ac
- include/Makefile.am
- include/msolve/msolve-data.h
- include/msolve/msolve.h
> fixes header files installation

- src/neogb/convert.c
- src/neogb/data.h
- src/neogb/f4.c
- src/neogb/meta_data.c
Caches the minimal degree of the first degree  fall appearing in f4.
> Falling degrees

- src/upolmat/nmod_mat_left_nullspace.c
perm_one -> perm_set_one changed in FLINT recently.
> fix compilation issue with new function name

- src/neogb/convert.c
- src/neogb/data.c
- src/neogb/data.h
- src/neogb/f4.c
- src/neogb/hash.c
- src/neogb/io.c
- src/neogb/la_ff_16.c
- src/neogb/la_ff_32.c
- src/neogb/la_ff_8.c
- src/neogb/meta_data.c
New implementation for final gb reduction in f4.
> gb reduction

- configure.ac
- src/msolve/msolve.c
Fixes initialization of random linear form in order to fix undefined behaviour of realloc.
> Initialization of random linear form

- configure.ac
- src/msolve/Makefile.am
- src/neogb/Makefile.am
> Switches from -release to -version-info for libraries

- src/msolve/msolve.c
- src/neogb/io.c
- src/neogb/meta_data.c
Fixes bitsize checks for function pointer arithmetic etc.
> Bit check fixes

- src/neogb/io.c
Accidentally introduced via #145 .
> Removes debug printing

- src/upolmat/nmod_mat_poly_mbasis.c
This is making the file containing the M-Basis implementation quite more readable, by removing profiling and debugging code that is not needed anymore.
> clean mbasis file

- src/msolve/main.c
> bug fix (sets linalg option to 2 in low characteristic)

- configure.ac
> new minor release version number update

- src/msolve/main.c
Typo reported by @mahrud, thanks.
> Typo fixed

- configure.ac
v0.6.8, fixes bugs related to lifting
> prepares new minor release

- src/msolve/lifting-gb.c
> Change one additional uint64_t -> mp_limb_t

- configure.ac
> updates version numbering

- src/neogb/convert.c
- src/neogb/hash.c
- src/neogb/la_ff_16.c
- src/neogb/la_ff_32.c
- src/neogb/la_ff_8.c
- src/neogb/symbol.c
This fixes some issues found via #216 
1. Handles more exception cases if the OS cannot provide more memory.
2. Fixes situation where sizes for memory (re-)allocations where falsely computed.
> Better excpetion handling

- src/crt/mpq_reconstruct.c
This is just a code cleaning PR (removes an unused function ; I should have done this in the previous PR)
> removes unused function
